"""add comentarios, users and ordenes trabajo tables

Revision ID: 1646c6b19bbe
Revises: a678401c76af
Create Date: 2025-08-06 16:23:18.509514

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1646c6b19bbe'
down_revision = 'a678401c76af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas_externas_toa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_externas_toa_active'))

    op.drop_table('empresas_externas_toa')
    with op.batch_alter_table('historia_ot_empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historia_ot_empresas_active'))

    op.drop_table('historia_ot_empresas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_ot_empresas',
    sa.Column('zona', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('orden_de_trabajo', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tecnico', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('coord_x', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('coord_y', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('duracion', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('flag_consulta_vecino', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('flag_estado_aprovision', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('flag_fallas_masivas', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('flag_materiales', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('flag_niveles', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('hora_flag_estado_aprovision', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('hora_flag_fallas_masivas', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('hora_flag_materiales', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('hora_flag_niveles', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('inicio', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('intervencion_neutra', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('notas_consulta_vecino', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('notas_consulta_vecino_ultimo', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('qr_drop', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('rut_tecnico', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tipo_red_producto', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('hora_ultima_vecino', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('hora_qr', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tipo_actividad', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('zona_de_trabajo', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('historia_ot_empresas_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('historia_ot_empresas_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('historia_ot_empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historia_ot_empresas_active'), ['active'], unique=False)

    op.create_table('empresas_externas_toa',
    sa.Column('nombre', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('nombre_toa', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('rut', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('empresas_externas_toa_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('empresas_externas_toa_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('empresas_externas_toa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_externas_toa_active'), ['active'], unique=False)

    # ### end Alembic commands ###
