"""add pasos and pelo

Revision ID: 23966301910c
Revises: d2023945e965
Create Date: 2025-08-08 16:15:18.555759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23966301910c'
down_revision = 'd2023945e965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historia_ot_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasos', sa.String(length=8000), nullable=True))
        batch_op.add_column(sa.Column('pelo', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historia_ot_empresas', schema=None) as batch_op:
        batch_op.drop_column('pelo')
        batch_op.drop_column('pasos')

    # ### end Alembic commands ###
