"""add_tecnicos_supervisores_table

Revision ID: 7e69443ab647
Revises: e8bc208e31ea
Create Date: 2025-08-08 14:06:30.671132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e69443ab647'
down_revision = 'e8bc208e31ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tecnicos_supervisores',
    sa.Column('nombre_tecnico', sa.String(length=128), nullable=False),
    sa.Column('rut_tecnico', sa.String(length=16), nullable=False),
    sa.Column('nombre_supervisor', sa.String(length=128), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas_externas_toa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('tecnicos_supervisores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tecnicos_supervisores_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnicos_supervisores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tecnicos_supervisores_active'))

    op.drop_table('tecnicos_supervisores')
    # ### end Alembic commands ###
