"""create tables empresas externas and historia ot

Revision ID: a678401c76af
Revises: 
Create Date: 2025-08-06 07:58:58.355160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a678401c76af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas_externas_toa',
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('nombre_toa', sa.String(length=128), nullable=False),
    sa.Column('rut', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('empresas_externas_toa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_externas_toa_active'), ['active'], unique=False)

    op.create_table('historia_ot_empresas',
    sa.Column('zona', sa.String(length=64), nullable=False),
    sa.Column('orden_de_trabajo', sa.String(length=64), nullable=False),
    sa.Column('empresa', sa.String(length=128), nullable=False),
    sa.Column('tecnico', sa.String(length=128), nullable=False),
    sa.Column('coord_x', sa.String(length=32), nullable=False),
    sa.Column('coord_y', sa.String(length=32), nullable=False),
    sa.Column('duracion', sa.String(length=128), nullable=False),
    sa.Column('estado', sa.String(length=128), nullable=False),
    sa.Column('fecha', sa.String(length=128), nullable=False),
    sa.Column('flag_consulta_vecino', sa.String(length=128), nullable=False),
    sa.Column('flag_estado_aprovision', sa.String(length=128), nullable=False),
    sa.Column('flag_fallas_masivas', sa.String(length=128), nullable=False),
    sa.Column('flag_materiales', sa.String(length=128), nullable=False),
    sa.Column('flag_niveles', sa.String(length=128), nullable=False),
    sa.Column('hora_flag_estado_aprovision', sa.String(length=128), nullable=False),
    sa.Column('hora_flag_fallas_masivas', sa.String(length=128), nullable=False),
    sa.Column('hora_flag_materiales', sa.String(length=128), nullable=False),
    sa.Column('hora_flag_niveles', sa.String(length=128), nullable=False),
    sa.Column('inicio', sa.String(length=128), nullable=False),
    sa.Column('intervencion_neutra', sa.String(length=128), nullable=False),
    sa.Column('notas_consulta_vecino', sa.String(length=8000), nullable=True),
    sa.Column('notas_consulta_vecino_ultimo', sa.String(length=8000), nullable=True),
    sa.Column('qr_drop', sa.String(length=128), nullable=False),
    sa.Column('rut_tecnico', sa.String(length=128), nullable=False),
    sa.Column('tipo_red_producto', sa.String(length=128), nullable=False),
    sa.Column('hora_ultima_vecino', sa.String(length=128), nullable=True),
    sa.Column('hora_qr', sa.String(length=128), nullable=False),
    sa.Column('tipo_actividad', sa.String(length=128), nullable=False),
    sa.Column('zona_de_trabajo', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('historia_ot_empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historia_ot_empresas_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historia_ot_empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historia_ot_empresas_active'))

    op.drop_table('historia_ot_empresas')
    with op.batch_alter_table('empresas_externas_toa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_externas_toa_active'))

    op.drop_table('empresas_externas_toa')
    # ### end Alembic commands ###
