"""add num ticket to comentarios

Revision ID: a970465e761a
Revises: bfcbecca0b16
Create Date: 2025-08-08 09:54:43.266770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a970465e761a'
down_revision = 'bfcbecca0b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_ticket', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('num_ticket')

    # ### end Alembic commands ###
