"""add_image_fields_to_comentarios

Revision ID: d2023945e965
Revises: 7e69443ab647
Create Date: 2025-08-08 15:10:37.482018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2023945e965'
down_revision = '7e69443ab647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('imagen_original_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('imagen_original_name')
        batch_op.drop_column('imagen_path')

    # ### end Alembic commands ###
