"""add_unique_constraint_to_orden_trabajo_codigo

Revision ID: e8bc208e31ea
Revises: 26cf50eee24a
Create Date: 2025-08-08 13:06:00.595286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bc208e31ea'
down_revision = '26cf50eee24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
